---
title: "Essay II"
author: "João Ricardo Tonin"
date: "03/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "")
getwd()

{ 
  # Check if the packages that we need are installed
  want = c("tidyverse", "plm", "texreg", "lmtest", "tibble")
  have = want %in% rownames(installed.packages())
  # Install the packages that we miss
  if ( any(!have) ) { install.packages( want[!have] ) }
  # Load the packages
  junk <- lapply(want, library, character.only = T)
  # Remove the objects we created
  rm(have, want, junk)
} # Import packages

```

```{r reading_databases, include=FALSE, echo=TRUE}

# reading databases
LBASE1 = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE1_Essay_II.rds"))
LBASE1c = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE1c_Essay_II.rds"))
LBASE2 = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE2_Essay_II.rds"))
LBASE2c = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE2c_Essay_II.rds"))

```

```{r databases, warning=FALSE, message=FALSE, error=FALSE, include=TRUE, echo = FALSE}

{
# organizing database
dLBASE1 = LBASE1 %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr, airline) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE1$group = dLBASE1 %>% group_indices(time)

# transforming to panel data
dLBASE1 = pdata.frame(dLBASE1, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE1

{
# organizing database
dLBASE1c = LBASE1c %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr, airline) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE1c$group = dLBASE1c %>% group_indices(time)

# transforming to panel data
dLBASE1c = pdata.frame(dLBASE1c, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE1c

{
# organizing database
dLBASE2 = LBASE2 %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE2$group = dLBASE2 %>% group_indices(time)

# transforming to panel data
dLBASE2 = pdata.frame(dLBASE2, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE2

{
# organizing database
dLBASE2c = LBASE2c %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE2c$group = dLBASE2c %>% group_indices(time)

# transforming to panel data
dLBASE2c = pdata.frame(dLBASE2c, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE2c

```

```{r equation, include=FALSE}

## variables

# dependet price
# independent variables hubling | aircraft | flight_hours | distance | distance2 | paid_luggage | free_luggage | connection | X6.11 | X12.17 | X18.23
# dummies | Tourist | N | market | covid | covid_wave | quarter | airline
# arrival dummies | ArrHUB | market_arr | region_arr | capital_arr 
# departure dummies | DepHUB | market_dep | capital_dep | region_dep
# endogenous | seat_dem | RouteShare | RouteHHI
# independent instruments | nbank | deposits | credit_loan | m150price | m300price | m500price
# RouteShare instruments | m150RouteShare | m300RouteShare | m5000RouteShare
# RouteHHI instruments | m150RouteHHI | m300RouteHHI | m500RouteHHI
# seat_dem instruments | m150seat_dem | m300seat_dem | m500seat_dem

{

# equations  
eq1a = price ~  hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + factor(Tourist) + factor(N) + factor(market) + 
  factor(covid) + factor(covid_wave) + factor (quarter) + factor(airline) + factor(ArrHUB) + 
  factor(market_arr) + factor(region_arr) + factor(capital_arr) + RouteShare

eq1b = price ~  hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + factor(Tourist) + factor(N) + factor(market) + 
  factor(covid) + factor(covid_wave) + factor (quarter) + factor(airline) + factor(DepHUB) + 
  factor(market_dep) + factor(region_dep) + factor(capital_dep) + RouteShare

eq1c = price ~  hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + factor(Tourist) + factor(N) + factor(market) + 
  factor(covid) + factor(covid_wave) + factor (quarter) + factor(airline) + factor(DepHUB) + 
  factor(market_dep) + factor(region_dep) + factor(capital_dep) + RouteShare | . -RouteShare + nbank + 
  m150price + m150RouteShare

eq1d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:10) + lag(price, 2:10) + m150RouteShare 

eq1e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:10) + lag(price, 2:10) +
  m150RouteShare

} # dLBASE1 equation

```

```{r functions, include=FALSE}

# editing function of organizing database
tabgmm = function(model){
  
  # extracting parameters
  param = as.data.frame(matrix(c(list(model$args$model, 
                                      model$args$effect, model$args$transformation)), 
                             ncol = 1, byrow = TRUE))
  colnames(param) = c("coef")
  row.names(param) = c("model", "effect", "transformation")
  param = param %>% 
    mutate(coef = as.character(coef))
  
  # extracting sargan test statistics
  sargan = sargan(model)
  sargan = as.data.frame(list(round(sargan$statistic, 3), round(sargan$p.value, 3)))
  colnames(sargan) = c("coef","pvalue")
  row.names(sargan) = c("sargan")
  
  # extracting mtest statistics
  mtest = mtest(model, order = 2)
  mtest = as.data.frame(list(round(mtest$statistic, 3), round(mtest$p.value, 3)))
  colnames(mtest) = c("coef","pvalue")
  row.names(mtest) = c("mtest")
  
  # extracting waldtest coef. statistics
  pwaldtest = pwaldtest(model, param = "coef")
  pwaldtest = as.data.frame(list(round(pwaldtest$statistic, 3), round(pwaldtest$p.value, 3)))
  colnames(pwaldtest) = c("coef","pvalue")
  row.names(pwaldtest) = c("Wald coef")
  
  # organizing database
  coef = as.data.frame(coef(summary(model))) %>% 
    mutate(pvalue = round(`Pr(>|z|)`,3),
           coef = round(Estimate,3)) %>%
    select(coef, pvalue) 
  
  # merging dataframes
  res = bind_rows(coef, sargan, mtest, pwaldtest) %>%
    mutate(coef = as.character(coef),
           pvalue = as.character(pvalue)) %>%
    bind_rows(param)
  
  return(res)
}

# editing function of regression gmm model
reggmm = function(equation){
  
  # regressing equation 1
  a11 = pgmm(equation, dLBASE1, model = "onestep", effect="individual")
  
  # tabulation main results
  ra11 = tabgmm(a11)
  colnames(ra11) = c("ra11_c", "ra11_p")
  
  # regressing equation 2
  a12 = pgmm(equation, dLBASE1, model = "onestep", effect="twoways")
  
  # tabulation main results
  ra12 = tabgmm(a12)
  colnames(ra12) = c("ra12_c", "ra12_p")
  
  # regressing equation 3
  a13 = pgmm(equation, dLBASE1, model = "twosteps", effect="individual")
  
  # tabulation main results
  ra13 = tabgmm(a13)
  colnames(ra13) = c("ra13_c", "ra13_p")
  
  # regressing equation 4
  a14 = pgmm(equation, dLBASE1, model = "twosteps", effect="twoways")
  
  # tabulation main results
  ra14 = tabgmm(a14)
  colnames(ra14) = c("ra14_c", "ra14_p")
  
  # regressing equation 5
  a15 = pgmm(equation, dLBASE1, model = "twosteps", effect="individual",colapse = TRUE)
  
  # tabulation main results
  ra15 = tabgmm(a15)
  colnames(ra15) = c("ra15_c", "ra15_p")
  
  # regressing equation 6
  a16 = pgmm(equation, dLBASE1, model = "twosteps", effect="twoways", colapse = TRUE)
  
  # tabulation main results
  ra16 = tabgmm(a16)
  colnames(ra16) = c("ra16_c", "ra16_p")
  
  # regressing equation 7
  a17 = pgmm(equation, dLBASE1, model = "twosteps", effect="twoways", colapse = TRUE, 
           transformation = "ld")
  
  # tabulation main results
  ra17 = tabgmm(a17)
  colnames(ra17) = c("ra17_c", "ra17_p")
  
  # regressing equation 7
  a18 = pgmm(equation, dLBASE1, model = "twosteps", effect="twoways", colapse = TRUE, 
           transformation = "ld")
  
  # tabulation main results
  ra18 = tabgmm(a18)
  colnames(ra18) = c("ra18_c", "ra18_p")
  
    # merging databases
  table = bind_cols(ra11, ra12, ra13, ra14, ra15, ra16, ra17, ra18)
  
  return(table)
}

```

```{r reg1_2sls, include = FALSE, error = TRUE}

# 2SLS

ols1 = plm(eq1a, data = dLBASE1)
fe1 =  update(ols1, effect = "individual")
ols2 = plm(eq1b, data = dLBASE1)
fe2 =  update(ols2, effect = "individual")
ivfe = update(fe2, eq1c)

# joining regression results
screenreg(list(ols1 = ols1, fe1 = fe1, ols2  = ols2, fe2 = fe2, ivfe = ivfe),
               digits = 3, omit.coef = "(Intercept)")

```

```{r gmm_1, include=FALSE, error=TRUE}

# setting directory 
setwd("C:/TESE/GITHUB/thesis_essay_ii/results/base1")

# defining types of gmm's equation
gmm1a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:10) + lag(price, 2:10) + m150RouteShare 
gmm1b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:20) + lag(price, 2:20) + m150RouteShare 
gmm1c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:30) + lag(price, 2:30) + m150RouteShare 
gmm1d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:40) + lag(price, 2:40) + m150RouteShare  
gmm1e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:50) + lag(price, 2:50) + m150RouteShare

# executing all regression
resgmm1a = reggmm(gmm1a)
saveRDS(resgmm1a, "resgmm1a.rds")

resgmm1b = reggmm(gmm1b)
saveRDS(resgmm1b, "resgmm1b.rds")

resgmm1c = reggmm(gmm1c)
saveRDS(resgmm1c, "resgmm1c.rds")

resgmm1d = reggmm(gmm1d)
saveRDS(resgmm1d, "resgmm1d.rds")

resgmm1e = reggmm(gmm1e)
saveRDS(resgmm1e, "resgmm1e.rds")

# defining types of gmm's equation
gmm2a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:10) + lag(price, 2:10) + m150seat_dem 
gmm2b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:20) + lag(price, 2:20) + m150seat_dem 
gmm2c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:30) + lag(price, 2:30) + m150seat_dem 
gmm2d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:40) + lag(price, 2:40) + m150seat_dem  
gmm2e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:50) + lag(price, 2:50) + m150seat_dem

# executing all regression
resgmm2a = reggmm(gmm2a)
saveRDS(resgmm2a, "resgmm2a.rds")

resgmm2b = reggmm(gmm2b)
saveRDS(resgmm2b, "resgmm2b.rds")

resgmm2c = reggmm(gmm2c)
saveRDS(resgmm2c, "resgmm2c.rds")

resgmm2d = reggmm(gmm2d)
saveRDS(resgmm2d, "resgmm2d.rds")

resgmm2e = reggmm(gmm2e)
saveRDS(resgmm2e, "resgmm2e.rds")


# defining types of gmm's equation
gmm3a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:10) + lag(price, 2:10) + m150RouteHHI 
gmm3b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:20) + lag(price, 2:20) + m150RouteHHI 
gmm3c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:30) + lag(price, 2:30) + m150RouteHHI 
gmm3d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:40) + lag(price, 2:40) + m150RouteHHI  
gmm3e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:50) + lag(price, 2:50) + m150RouteHHI

# executing all regression
resgmm3a = reggmm(gmm3a)
saveRDS(resgmm3a, "resgmm3a.rds")

resgmm3b = reggmm(gmm3b)
saveRDS(resgmm3b, "resgmm3b.rds")

resgmm3c = reggmm(gmm3c)
saveRDS(resgmm3c, "resgmm3c.rds")

resgmm3d = reggmm(gmm3d)
saveRDS(resgmm3d, "resgmm3d.rds")

resgmm3e = reggmm(gmm3e)
saveRDS(resgmm3e, "resgmm3e.rds")

```

```{r gmm_1c, include=FALSE, error=TRUE}

# adjusting database
dLBASE1 = dLBASE1c

# setting directory 
setwd("C:/TESE/GITHUB/thesis_essay_ii/results/base1c")

# defining types of gmm's equation
gmm1a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:10) + lag(price, 2:10) + m150RouteShare 
gmm1b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:20) + lag(price, 2:20) + m150RouteShare 
gmm1c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:30) + lag(price, 2:30) + m150RouteShare 
gmm1d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:40) + lag(price, 2:40) + m150RouteShare  
gmm1e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:50) + lag(price, 2:50) + m150RouteShare

# executing all regression
resgmm1a = reggmm(gmm1a)
saveRDS(resgmm1a, "resgmm1a.rds")

resgmm1b = reggmm(gmm1b)
saveRDS(resgmm1b, "resgmm1b.rds")

resgmm1c = reggmm(gmm1c)
saveRDS(resgmm1c, "resgmm1c.rds")

resgmm1d = reggmm(gmm1d)
saveRDS(resgmm1d, "resgmm1d.rds")

resgmm1e = reggmm(gmm1e)
saveRDS(resgmm1e, "resgmm1e.rds")

# defining types of gmm's equation
gmm2a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:10) + lag(price, 2:10) + m150seat_dem 
gmm2b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:20) + lag(price, 2:20) + m150seat_dem 
gmm2c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:30) + lag(price, 2:30) + m150seat_dem 
gmm2d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:40) + lag(price, 2:40) + m150seat_dem  
gmm2e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:50) + lag(price, 2:50) + m150seat_dem

# executing all regression
resgmm2a = reggmm(gmm2a)
saveRDS(resgmm2a, "resgmm2a.rds")

resgmm2b = reggmm(gmm2b)
saveRDS(resgmm2b, "resgmm2b.rds")

resgmm2c = reggmm(gmm2c)
saveRDS(resgmm2c, "resgmm2c.rds")

resgmm2d = reggmm(gmm2d)
saveRDS(resgmm2d, "resgmm2d.rds")

resgmm2e = reggmm(gmm2e)
saveRDS(resgmm2e, "resgmm2e.rds")


# defining types of gmm's equation
gmm3a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:10) + lag(price, 2:10) + m150RouteHHI 
gmm3b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:20) + lag(price, 2:20) + m150RouteHHI 
gmm3c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:30) + lag(price, 2:30) + m150RouteHHI 
gmm3d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:40) + lag(price, 2:40) + m150RouteHHI  
gmm3e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  connection + X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:50) + lag(price, 2:50) + m150RouteHHI

# executing all regression
resgmm3a = reggmm(gmm3a)
saveRDS(resgmm3a, "resgmm3a.rds")

resgmm3b = reggmm(gmm3b)
saveRDS(resgmm3b, "resgmm3b.rds")

resgmm3c = reggmm(gmm3c)
saveRDS(resgmm3c, "resgmm3c.rds")

resgmm3d = reggmm(gmm3d)
saveRDS(resgmm3d, "resgmm3d.rds")

resgmm3e = reggmm(gmm3e)
saveRDS(resgmm3e, "resgmm3e.rds")

```

```{r gmm_2, include=FALSE, error=TRUE}

# adjusting database
dLBASE1 = dLBASE2

# setting directory 
setwd("C:/TESE/GITHUB/thesis_essay_ii/results/base2")

# defining types of gmm's equation
gmm1a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:10) + lag(price, 2:10) + m150RouteShare 
gmm1b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:20) + lag(price, 2:20) + m150RouteShare 
gmm1c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:30) + lag(price, 2:30) + m150RouteShare 
gmm1d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:40) + lag(price, 2:40) + m150RouteShare  
gmm1e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:50) + lag(price, 2:50) + m150RouteShare

# executing all regression
resgmm1a = reggmm(gmm1a)
saveRDS(resgmm1a, "resgmm1a.rds")

resgmm1b = reggmm(gmm1b)
saveRDS(resgmm1b, "resgmm1b.rds")

resgmm1c = reggmm(gmm1c)
saveRDS(resgmm1c, "resgmm1c.rds")

resgmm1d = reggmm(gmm1d)
saveRDS(resgmm1d, "resgmm1d.rds")

resgmm1e = reggmm(gmm1e)
saveRDS(resgmm1e, "resgmm1e.rds")

# defining types of gmm's equation
gmm2a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:10) + lag(price, 2:10) + m150seat_dem 
gmm2b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:20) + lag(price, 2:20) + m150seat_dem 
gmm2c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:30) + lag(price, 2:30) + m150seat_dem 
gmm2d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:40) + lag(price, 2:40) + m150seat_dem  
gmm2e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:50) + lag(price, 2:50) + m150seat_dem

# executing all regression
resgmm2a = reggmm(gmm2a)
saveRDS(resgmm2a, "resgmm2a.rds")

resgmm2b = reggmm(gmm2b)
saveRDS(resgmm2b, "resgmm2b.rds")

resgmm2c = reggmm(gmm2c)
saveRDS(resgmm2c, "resgmm2c.rds")

resgmm2d = reggmm(gmm2d)
saveRDS(resgmm2d, "resgmm2d.rds")

resgmm2e = reggmm(gmm2e)
saveRDS(resgmm2e, "resgmm2e.rds")


# defining types of gmm's equation
gmm3a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:10) + lag(price, 2:10) + m150RouteHHI 
gmm3b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:20) + lag(price, 2:20) + m150RouteHHI 
gmm3c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:30) + lag(price, 2:30) + m150RouteHHI 
gmm3d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:40) + lag(price, 2:40) + m150RouteHHI  
gmm3e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:50) + lag(price, 2:50) + m150RouteHHI

# executing all regression
resgmm3a = reggmm(gmm3a)
saveRDS(resgmm3a, "resgmm3a.rds")

resgmm3b = reggmm(gmm3b)
saveRDS(resgmm3b, "resgmm3b.rds")

resgmm3c = reggmm(gmm3c)
saveRDS(resgmm3c, "resgmm3c.rds")

resgmm3d = reggmm(gmm3d)
saveRDS(resgmm3d, "resgmm3d.rds")

resgmm3e = reggmm(gmm3e)
saveRDS(resgmm3e, "resgmm3e.rds")

```

```{r gmm_2c, include=FALSE, error=TRUE}

# adjusting database
dLBASE1 = dLBASE2c

# setting directory 
setwd("C:/TESE/GITHUB/thesis_essay_ii/results/base2c")

# defining types of gmm's equation
gmm1a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:10) + lag(price, 2:10) + m150RouteShare 
gmm1b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:20) + lag(price, 2:20) + m150RouteShare 
gmm1c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:30) + lag(price, 2:30) + m150RouteShare 
gmm1d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:40) + lag(price, 2:40) + m150RouteShare  
gmm1e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:50) + lag(price, 2:50) + m150RouteShare

# executing all regression
resgmm1a = reggmm(gmm1a)
saveRDS(resgmm1a, "resgmm1a.rds")

resgmm1b = reggmm(gmm1b)
saveRDS(resgmm1b, "resgmm1b.rds")

resgmm1c = reggmm(gmm1c)
saveRDS(resgmm1c, "resgmm1c.rds")

resgmm1d = reggmm(gmm1d)
saveRDS(resgmm1d, "resgmm1d.rds")

resgmm1e = reggmm(gmm1e)
saveRDS(resgmm1e, "resgmm1e.rds")

# defining types of gmm's equation
gmm2a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:10) + lag(price, 2:10) + m150seat_dem 
gmm2b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:20) + lag(price, 2:20) + m150seat_dem 
gmm2c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:30) + lag(price, 2:30) + m150seat_dem 
gmm2d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:40) + lag(price, 2:40) + m150seat_dem  
gmm2e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + seat_dem | lag(seat_dem, 1:50) + lag(price, 2:50) + m150seat_dem

# executing all regression
resgmm2a = reggmm(gmm2a)
saveRDS(resgmm2a, "resgmm2a.rds")

resgmm2b = reggmm(gmm2b)
saveRDS(resgmm2b, "resgmm2b.rds")

resgmm2c = reggmm(gmm2c)
saveRDS(resgmm2c, "resgmm2c.rds")

resgmm2d = reggmm(gmm2d)
saveRDS(resgmm2d, "resgmm2d.rds")

resgmm2e = reggmm(gmm2e)
saveRDS(resgmm2e, "resgmm2e.rds")


# defining types of gmm's equation
gmm3a = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:10) + lag(price, 2:10) + m150RouteHHI 
gmm3b = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:20) + lag(price, 2:20) + m150RouteHHI 
gmm3c = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:30) + lag(price, 2:30) + m150RouteHHI 
gmm3d = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:40) + lag(price, 2:40) + m150RouteHHI  
gmm3e = price ~ lag(price) + hubling + aircraft + flight_hours + paid_luggage + free_luggage + 
  X6.11 + X12.17 + X18.23 + RouteHHI | lag(RouteHHI, 1:50) + lag(price, 2:50) + m150RouteHHI

# executing all regression
resgmm3a = reggmm(gmm3a)
saveRDS(resgmm3a, "resgmm3a.rds")

resgmm3b = reggmm(gmm3b)
saveRDS(resgmm3b, "resgmm3b.rds")

resgmm3c = reggmm(gmm3c)
saveRDS(resgmm3c, "resgmm3c.rds")

resgmm3d = reggmm(gmm3d)
saveRDS(resgmm3d, "resgmm3d.rds")

resgmm3e = reggmm(gmm3e)
saveRDS(resgmm3e, "resgmm3e.rds")

```



```{r 2SLS, include=FALSE}

# 2SLS

ols = plm(OLS, data = dLBASE1, effect = "time")
fe =  update(ols, effect = "twoways")
ivfe = update(fe, . ~ . | . -endo + z5)

# joining regression results
screenreg(list(ols   = ols,  fe   = fe, ivfe  = ivfe),
               digits = 3, omit.coef = "(Intercept)")

# tests 

## instrument relevance

# first stage: regress endogenous variable with all exogenous variables
fs = plm(FS, data = dLBASE1, effect = "twoways")

# second stage: regress first stage equation without z's variables
instrFtest = waldtest(fs, . ~ . -z5 )
print(instrFtest) # H0: instruments are irrelevants -> needs p_valor < 0,10 


## exogeneity test

# first stage: idem fs estimation

# second stage: regress normal equation with fs$residuals as independent variable
Hausman_reg = plm(HR, data = dLBASE1, effect = "twoways")
print(summary(Hausman_reg))

# third stage: execute Wu-Hausman exogeneity test
HausWutest = waldtest(Hausman_reg,.~.-fs$residuals)
print(HausWutest) # H0: residuals are irrelevants -> needs p_valor > 0.10


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# ec2sls

w1 = plm(W1, data = dLBASE1, model = "within")
r1 = update(w1, model = "random", random.method = "nerlove",
            random.dfcor = c(3, 3), inst.method = "baltagi")

# Hausman test
phtest(w1, r1) # H1: one model is inconsistent - p_valor < 0,10 : within


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# ht2sls

# ec
ht1r = plm(W1, data = dLBASE1, model = "random", 
           inst.method = "baltagi", random.method = "ht")

# w
ht1w = plm(W1, data = dLBASE1, model = "within", 
           inst.method = "baltagi", random.method = "ht")

# Hausman test
phtest(ht1w, ht1r)

```



